apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rating-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: cicd.tmax.io/v1
kind: IntegrationConfig
metadata:
  name: bookinfo-rating-config
spec:
  git:
    type: github
    apiUrl: 
    repository: tmax-cloud/bookinfo-rating
    token:
      valueFrom:
        secretKeyRef:
          name: yxzzzxh-git-token
          key: token
  workspaces:
    - name : rating-workspace
      persistentVolumeClaim:
        claimName: rating-pvc
  secrets:
    - name : tmaxcloudck-docker-hub-secret
  jobs:
    postSubmit:
      - name: gradle-package
        image: docker.io/gradle:7.3.1-jdk11
        script: |
          gradle build
          cp build/libs/$JAR_NAME $(workspaces.rating-workspace.path)/$JAR_NAME
        env: 
          - name: JAR_NAME
            value : rating.jar
        when:
          tag:
            - v.*
      - name: build-and-push
        image: quay.io/buildah/stable
        script: |
          IMG_TAG=${CI_HEAD_REF#refs/tags/}

          cp $(workspaces.rating-workspace.path)/$JAR_NAME ./
          buildah bud --tls-verify=false --storage-driver=vfs --format docker -f Dockerfile -t $IMG_URL:$IMG_TAG .
          buildah login --tls-verify=false -u $HARBOR_USER -p $HARBOR_PASS core.hr.172.22.11.16.nip.io
          buildah push --tls-verify=false --storage-driver=vfs $IMG_URL:$IMG_TAG docker://$IMG_URL:$IMG_TAG
        env:
          - name: IMG_URL
            value: core.hr.172.22.11.16.nip.io/shinhan-bookinfo/bookinfo-rating
          - name: JAR_NAME
            value: rating.jar
          - name: HARBOR_USER
            value: admin
          - name: HARBOR_PASS
            value: admin
        securityContext:
          privileged: true
        after:
          - gradle-package
        when:
          tag:
            - v.*
